spring:
  application:
    name: order-service
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:local},topics
  config:
    import: "optional:configserver:"
  cloud:
    config:
      discovery:
        enabled: true
        service-id: config-server

server:
  port: 9007

eureka:
  client:
    service-url:
      defaultZone: http://localhost:9001/eureka/
    register-with-eureka: true
    fetch-registry: true
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}

---
spring:
  config:
    activate:
      on-profile: local
eureka:
  client:
    register-with-eureka: false
    fetch-registry: false

---
spring:
  config:
    activate:
      on-profile: prod
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true