services:
  order-service:
    image: ${IMAGE}:${IMAGE_TAG:-latest}
    env_file: .env
    environment:
      SPRING_PROFILES_ACTIVE: dev
    ports:
      - "9007:9007"
    volumes:
      - /home/deploy/ssl/kafka.truststore.jks:/app/ssl/kafka.truststore.jks:ro
      - order-logs:/app/logs
    restart: unless-stopped
    networks:
      - goggles-network

volumes:
  order-logs:

networks:
  goggles-network:
    external: true